<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coffee Manager</title>
<link type="text/css" rel="stylesheet" href="/static/libs/webix/webix.css">

<#--    <link rel="stylesheet" type="text/css" href="http://cdn.webix.com/edge/webix.css">-->
<#--    <script type="text/javascript" src="http://cdn.webix.com/edge/webix.js"></script>-->

    <link rel="stylesheet" href="//cdn.webix.com/materialdesignicons/5.8.95/css/materialdesignicons.min.css?v=8.3.0" type="text/css" charset="utf-8">

    <link type="text/css" rel="stylesheet" href="/libs/webix/webix.css">
    <script src="/libs/webix/webix.js"></script>
    <script src="/libs/routie.min.js"></script>
    <script data-main="js/index" src="/libs/require.min.js"></script>
</head>
<body>
    <div id="app"></div>
</body>
</html>