<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logistic</title>
<link type="text/css" rel="stylesheet" href="/static/libs/webix/webix.css">

    <link rel="stylesheet" type="text/css" href="http://cdn.webix.com/edge/webix.css">
    <script type="text/javascript" src="http://cdn.webix.com/edge/webix.js"></script>

    <script src="/static/libs/webix/webix.js"></script>
    <script src="/static/libs/routie.min.js"></script>
<#--        <script src="/static/js/index.js"></script>-->
    <script data-main="/static/js/index" src="/static/libs/require.min.js"></script>
</head>
<body>
    <div id="app"></div>
</body>
</html>