<#import "parts/common.ftlh" as c>
<@c.page>
<main class="container-fluid">
    <table class="table">
        <thead>
            <th score="col">Категория</th>
            <th score="col">Наименование</th>
            <th score="col">Объем/вес</th>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Кофе</th>
                <td>Капучино</td>
                <td>350ml</td>
            </tr>
        </tbody>
    </table>
</main>
</@c.page>